// <auto-generated />
namespace Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Customer_AddColumn_DateOfBirth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer_AddColumn_DateOfBirth));
        
        string IMigrationMetadata.Id
        {
            get { return "202108102012324_Customer_AddColumn_DateOfBirth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
